compile:
	## Compile

	# First step
	@echo 'some output'

	# Second step
	@echo 'other output'

clean:

	## Clean
	# Clean dist
	@echo 'cleaning /dist'

break:
	## Failing task

	# Try something that works
	@echo 'that was easy'

	# Trying something desperate
	@thiswillbreak
